## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [2]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [48]:
y_1 = y[y==1]
y_0 = y[y==0]
X_1 = X[:len(y_1)]
X_0 = X[:len(y_0)]

from sklearn.model_selection import train_test_split
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X_1, y_1, test_size=(10/40), random_state=0)
X_train_0, X_test_0, y_train_0, y_test_0 = train_test_split(X_0, y_0, test_size=(10/160), random_state=0)

print(f' X_test_1\n {X_test_1}')
print(f'\n y_test_1\n {y_test_1}')
print(f'\n X_test_0\n {X_test_0}')
print(f'\n y_test_0\n {y_test_0}')

 X_test_1
 [[110 111 112 113 114]
 [100 101 102 103 104]
 [125 126 127 128 129]
 [ 20  21  22  23  24]
 [ 50  51  52  53  54]
 [ 75  76  77  78  79]
 [140 141 142 143 144]
 [ 55  56  57  58  59]
 [ 90  91  92  93  94]
 [145 146 147 148 149]]

 y_test_1
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

 X_test_0
 [[550 551 552 553 554]
 [560 561 562 563 564]
 [715 716 717 718 719]
 [ 35  36  37  38  39]
 [220 221 222 223 224]
 [505 506 507 508 509]
 [610 611 612 613 614]
 [330 331 332 333 334]
 [425 426 427 428 429]
 [430 431 432 433 434]]

 y_test_0
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [49]:
X_test, y_test = np.concatenate((X_test_1, X_test_0)), np.concatenate((y_test_1, y_test_0))
X_train, y_train = np.concatenate((X_train_1, X_train_0)), np.concatenate((y_train_1, y_train_0))

print(f' X_test shape:{X_test.shape}\n {X_test}')
print(f'\n y_test shape:{y_test.shape}\n {y_test}')

 X_test shape:(20, 5)
 [[110 111 112 113 114]
 [100 101 102 103 104]
 [125 126 127 128 129]
 [ 20  21  22  23  24]
 [ 50  51  52  53  54]
 [ 75  76  77  78  79]
 [140 141 142 143 144]
 [ 55  56  57  58  59]
 [ 90  91  92  93  94]
 [145 146 147 148 149]
 [550 551 552 553 554]
 [560 561 562 563 564]
 [715 716 717 718 719]
 [ 35  36  37  38  39]
 [220 221 222 223 224]
 [505 506 507 508 509]
 [610 611 612 613 614]
 [330 331 332 333 334]
 [425 426 427 428 429]
 [430 431 432 433 434]]

 y_test shape:(20,)
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
