# 作業目標:
了解 Convolution 卷積的組成

# 作業重點:
修改 a_slice_prev, 檢查 Z 的輸出

In [0]:
import numpy as np

In [0]:
# GRADED FUNCTION: conv_single_step
def conv_single_step(a_slice_prev, W, b):
    """
    定義一層 Kernel (內核), 使用的參數說明如下
    Arguments:
        a_slice_prev -- 輸入資料的維度
        W -- 權重, 被使用在 a_slice_prev
        b -- 偏差參數 
    Returns:
        Z -- 滑動窗口（W，b）卷積在前一個 feature map 上的結果
    """

    # 定義一個元素介於 a_slice and W
    s = a_slice_prev * W
    # 加總所有的 "s" 並指定給Z.
    Z = np.sum(s)
    # Add bias b to Z. 這是 float() 函數,
    Z = float(Z + b)

    return Z

In [3]:
np.random.seed(10)

#定義一個 2x2x3 的 feature map
a_slice_prev = np.random.randn(2, 2, 3)
W = np.random.randn(2, 2, 3)
b = np.random.randn(1, 1, 1)
print(f"a_slice_prev: \n{a_slice_prev}\n")
print(f"W: \n{W}\n")
print(f"b: \n{b}\n")

a_slice_prev: 
[[[ 1.3315865   0.71527897 -1.54540029]
  [-0.00838385  0.62133597 -0.72008556]]

 [[ 0.26551159  0.10854853  0.00429143]
  [-0.17460021  0.43302619  1.20303737]]]

W: 
[[[-0.96506567  1.02827408  0.22863013]
  [ 0.44513761 -1.13660221  0.13513688]]

 [[ 1.484537   -1.07980489 -1.97772828]
  [-1.7433723   0.26607016  2.38496733]]]

b: 
[[[1.12369125]]]



In [4]:
Z = conv_single_step(a_slice_prev, W, b)
print(f"Z = {Z}")

Z = 2.9708232791129827
